### ISSUE TITLE
Action: Use kupfer_keyring to get secret of an item (object) from seahorse?

### ISSUE THREAD

**Issue by khurshid-alam** [hugosenari/Kupfer-Plugins#12]
It would be nice if we can search and find (paste secret to clipboard) secret of an item in Seahorse or anything that uses libsecret.

For example:

```python
#!/usr/bin/env python3
import secretstorage

bus = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(bus)
for item in collection.search_items({'rtm': 'rtm_api_key'}):
    print(item.get_secret())
    print(item.get_attributes())
```

Note: I only want to search those items which was created by me and **not by chrome/firefox**, .i.e which has `'xdg:schema': 'org.freedesktop.Secret.Generic'`

So we use `search_items` instead of `get_all_items` in keysource ⟶ 
```python
bus = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(bus)
for item in collection.search_items({'xdg:schema': 'org.freedesktop.Secret.Generic'}):
    print (item.get_label())
```

Thoughts?

**Comment by hugosenari** [comment]
**Two options:**

**Fork creating a kupfer_secretstorage plugin**:

Direct use of `secretstorage` has better performance but restrict your keys to secretstorage, `keyring` have [other backends](https://github.com/jaraco/keyring/tree/master/keyring/backends).

**Filter result of get_all_items**:

Filter before [Leaf creation](https://github.com/hugosenari/Kupfer-Plugins/blob/master/kupfer_keyring/kupfer_keyring.py#L58)
```python
for obj in self.resource.get_all_items():
    if obj.get('xdg:schema') == 'org.freedesktop.Secret.Generic'
        yield KeyLeaf(obj)
```


I'm inclined to implement both and add a setting to filter :smile:

**Comment by khurshid-alam** [comment]
So we can access secret storage backends with keyring? Can you give an example?

**Comment by khurshid-alam** [comment]
May be using Using secret from gi would be better. That would avoid hardcore dependency on these modules.

```python
gi.require_version('Secret', '1')
from gi.repository import Secret

#Example using gi
EXAMPLE_SCHEMA = Secret.Schema.new("org.freedesktop.Secret.Generic",
    Secret.SchemaFlags.NONE, {'rtm': Secret.SchemaAttributeType.STRING}
)
password = Secret.password_lookup_sync(EXAMPLE_SCHEMA, {'rtm': 'rtm_token'}, None)
print (password)
```

I will try and replicate above code with it.

**Comment by khurshid-alam** [comment]
This should be closed.
