### ISSUE TITLE
Fix Empathy plugin for Python 3

### ISSUE THREAD

**Issue by khurshid-alam** [hugosenari/Kupfer-Plugins#6]
It shows following error:

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 604, in msg_reply_handler
>     reply_handler(*message.get_args_list(**get_args_opts))
>   File "/usr/share/kupfer/kupfer/plugin/empathy.py", line 224, in <lambda>
>     'valid_account':valid_account}, *args, **kwds),
>   File "/usr/share/kupfer/kupfer/plugin/empathy.py", line 245, in _reply_handle_channels
>     for contact, details in contact_details.iteritems():
> AttributeError: 'dbus.Dictionary' object has no attribute 'iteritems'

**Fix:**
Just Remove `iteritems`

```diff
- for contact, details in contact_details.iteritems():
+ for contact, details in contact_details.items():

def get_items(self):
-    for status, name in _STATUSES.iteritems()
+   for status, name in _STATUSES.items():
```

**Comment by hugosenari** [comment]
Thank you!
Moving it to [new structure](https://github.com/hugosenari/Kupfer-Plugins/tree/master/empathetic)
